default:
    surf_var_weights: {
                'msl': 1.5,
                '10u': 0.77,
                '10v': 0.66,
                '2t': 3.0,
                'sst': 1.0,
                'ci': 1.0,
                'co2': 1.0,
                'zwd': 2.0,
                'tp_mswep' : 1.0,
            }
    atmos_var_weights: {
                'z': 2.8,
                'q': 0.78,
                't': 1.7,
                'u': 0.87,
                'v': 0.6
            }
